### ISSUE TITLE
Installation issue on Mac M2

### ISSUE THREAD

**Issue by microprediction** [qpsolvers/qpsolvers#204]
Just a note. Sorry haven't had time to dig in further. Was daqp a new addition? 

```
Collecting qpsolvers
  Using cached qpsolvers-3.3.0-py3-none-any.whl (75 kB)
Collecting daqp>=0.5.0
  Using cached daqp-0.5.0.tar.gz (131 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      Could not find daqp directory
      Traceback (most recent call last):
        File "/opt/homebrew/Caskroom/miniforge/base/envs/chattychatty/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/homebrew/Caskroom/miniforge/base/envs/chattychatty/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/opt/homebrew/Caskroom/miniforge/base/envs/chattychatty/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/02/plfpf9yd4yv2rwjmmvh6b4dc0000gn/T/pip-build-env-ek27kxkv/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/02/plfpf9yd4yv2rwjmmvh6b4dc0000gn/T/pip-build-env-ek27kxkv/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/02/plfpf9yd4yv2rwjmmvh6b4dc0000gn/T/pip-build-env-ek27kxkv/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 50, in <module>
        File "/private/var/folders/02/plfpf9yd4yv2rwjmmvh6b4dc0000gn/T/pip-build-env-ek27kxkv/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 973, in cythonize
          module_list, module_metadata = create_extension_list(
        File "/private/var/folders/02/plfpf9yd4yv2rwjmmvh6b4dc0000gn/T/pip-build-env-ek27kxkv/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 816, in create_extension_list
          for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
        File "/private/var/folders/02/plfpf9yd4yv2rwjmmvh6b4dc0000gn/T/pip-build-env-ek27kxkv/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 114, in nonempty
          raise ValueError(error_msg)
      ValueError: 'daqp.pyx' doesn't match any files
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
```

**Comment by darnstrom** [comment]
@microprediction @stephane-caron I found that a Cython file was not uploaded to PyPI in the 0.5.0 release of daqp (due to a typo in MANIFEST.in). Since this will yield problems if a wheel is not available, this could be the reason. The missing file is added in v0.5.1 of daqp, so ensuring that this version is installed with pip might resolve the problem.

**Comment by darnstrom** [comment]
Also, arm64 wheels for Mac is now available for daqp  v0.5.0 >=. This should address the issue more directly.

**Comment by stephane-caron** [comment]
OK, let's update this right away. PR: https://github.com/qpsolvers/qpsolvers/pull/205. Once it hits master let's release v3.3.1 to propagate the fix.

**Comment by stephane-caron** [comment]
And v3.3.1 is out. @microprediction could you try installing again to check if it works for you now?

**Comment by microprediction** [comment]
Works fine now, thx.

**Comment by stephane-caron** [comment]
Great, thanks for checking!
