### ISSUE TITLE
Installation error on Apple Silicon macOS

### ISSUE THREAD

**Issue by BarshaLamichhane** [qpsolvers/qpsolvers#296]
Hi, I am using macos and I tried to solve the issue using the same link:  https://github.com/qpsolvers/qpsolvers/issues/291
But my problem is not solved . I am facing following error while using `pip install qpsolvers`.

```
(Barsha) barshalamichhane@MOORE-01 src % python3 test.py                                  
Traceback (most recent call last):
  File "/Users/barshalamichhane/Documents/Laval_University/iid/nutrition_project/Barsha/src/test.py", line 8, in <module>
    from qpsolvers import solve_qp
  File "/Users/barshalamichhane/Documents/Laval_University/iid/nutrition_project/Barsha/lib/python3.12/site-packages/qpsolvers/__init__.py", line 9, in <module>
    from ._internals import available_solvers
  File "/Users/barshalamichhane/Documents/Laval_University/iid/nutrition_project/Barsha/lib/python3.12/site-packages/qpsolvers/_internals.py", line 11, in <module>
    from .solvers import available_solvers as supported_solvers
  File "/Users/barshalamichhane/Documents/Laval_University/iid/nutrition_project/Barsha/lib/python3.12/site-packages/qpsolvers/solvers/__init__.py", line 710, in <module>
    raise ImportError(
ImportError: no QP solver found on your system, you can install solvers from PyPI by ``pip install qpsolvers[open_source_solvers]``
(Barsha) barshalamichhane@MOORE-01 src % 
```

I again tried to install by using ``pip install qpsolvers[open_source_solvers]``. But again it shows following error :

 ```
Building wheels for collected packages: qdldl
        Building wheel for qdldl (pyproject.toml): started
        Building wheel for qdldl (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error
      
        × Building wheel for qdldl (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [72 lines of output]
            running bdist_wheel
            running build
            running build_ext
            Traceback (most recent call last):
              File "<string>", line 81, in build_extensions
              File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 466, in check_output
                return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 548, in run
                with Popen(*popenargs, **kwargs) as process:
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 1026, in __init__
                self._execute_child(args, executable, preexec_fn, close_fds,
              File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 1950, in _execute_child
                raise child_exception_type(errno_num, err_msg, err_filename)
            FileNotFoundError: [Errno 2] No such file or directory: 'cmake'
      
            During handling of the above exception, another exception occurred:
      
            Traceback (most recent call last):
              File "/Users/barshalamichhane/Documents/Laval_University/iid/nutrition_project/Barsha/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
                main()
              File "/Users/barshalamichhane/Documents/Laval_University/iid/nutrition_project/Barsha/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
                json_out['return_val'] = hook(**hook_input['kwargs'])
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/Users/barshalamichhane/Documents/Laval_University/iid/nutrition_project/Barsha/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
                return _build_backend().build_wheel(wheel_directory, config_settings,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/private/var/folders/5q/gqq_38qd7ygbjx8qx5hj512r0000gn/T/pip-build-env-skjkpqsa/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 410, in build_wheel
                return self._build_with_temp_dir(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/private/var/folders/5q/gqq_38qd7ygbjx8qx5hj512r0000gn/T/pip-build-env-skjkpqsa/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 395, in _build_with_temp_dir
                self.run_setup()
              File "/private/var/folders/5q/gqq_38qd7ygbjx8qx5hj512r0000gn/T/pip-build-env-skjkpqsa/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
                exec(code, locals())
              File "<string>", line 113, in <module>
              File "/private/var/folders/5q/gqq_38qd7ygbjx8qx5hj512r0000gn/T/pip-build-env-skjkpqsa/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 103, in setup
                return distutils.core.setup(**attrs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/private/var/folders/5q/gqq_38qd7ygbjx8qx5hj512r0000gn/T/pip-build-env-skjkpqsa/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 185, in setup
                return run_commands(dist)
                       ^^^^^^^^^^^^^^^^^^
              File "/private/var/folders/5q/gqq_38qd7ygbjx8qx5hj512r0000gn/T/pip-build-env-skjkpqsa/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
                dist.run_commands()
              File "/private/var/folders/5q/gqq_38qd7ygbjx8qx5hj512r0000gn/T/pip-build-env-skjkpqsa/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
                self.run_command(cmd)
              File "/private/var/folders/5q/gqq_38qd7ygbjx8qx5hj512r0000gn/T/pip-build-env-skjkpqsa/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 963, in run_command
                super().run_command(command)
              File "/private/var/folders/5q/gqq_38qd7ygbjx8qx5hj512r0000gn/T/pip-build-env-skjkpqsa/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
                cmd_obj.run()
              File "/private/var/folders/5q/gqq_38qd7ygbjx8qx5hj512r0000gn/T/pip-build-env-skjkpqsa/normal/lib/python3.12/site-packages/wheel/bdist_wheel.py", line 368, in run
                self.run_command("build")
              File "/private/var/folders/5q/gqq_38qd7ygbjx8qx5hj512r0000gn/T/pip-build-env-skjkpqsa/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
                self.distribution.run_command(command)
              File "/private/var/folders/5q/gqq_38qd7ygbjx8qx5hj512r0000gn/T/pip-build-env-skjkpqsa/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 963, in run_command
                super().run_command(command)
              File "/private/var/folders/5q/gqq_38qd7ygbjx8qx5hj512r0000gn/T/pip-build-env-skjkpqsa/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
                cmd_obj.run()
              File "/private/var/folders/5q/gqq_38qd7ygbjx8qx5hj512r0000gn/T/pip-build-env-skjkpqsa/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/build.py", line 131, in run
                self.run_command(cmd_name)
              File "/private/var/folders/5q/gqq_38qd7ygbjx8qx5hj512r0000gn/T/pip-build-env-skjkpqsa/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
                self.distribution.run_command(command)
              File "/private/var/folders/5q/gqq_38qd7ygbjx8qx5hj512r0000gn/T/pip-build-env-skjkpqsa/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 963, in run_command
                super().run_command(command)
              File "/private/var/folders/5q/gqq_38qd7ygbjx8qx5hj512r0000gn/T/pip-build-env-skjkpqsa/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
                cmd_obj.run()
              File "/private/var/folders/5q/gqq_38qd7ygbjx8qx5hj512r0000gn/T/pip-build-env-skjkpqsa/overlay/lib/python3.12/site-packages/setuptools/command/build_ext.py", line 89, in run
                _build_ext.run(self)
              File "/private/var/folders/5q/gqq_38qd7ygbjx8qx5hj512r0000gn/T/pip-build-env-skjkpqsa/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
                self.build_extensions()
              File "<string>", line 83, in build_extensions
            RuntimeError: CMake must be installed to build qdldl
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for qdldl
      Failed to build qdldl
      ERROR: Could not build wheels for qdldl, which is required to install pyproject.toml-based projects
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
(Barsha) barshalamichhane@MOORE-01 src % 


```

I also tried `pip install cmake` and again install the qpsolvers but again I am getting the same error. Please help with this.

**Comment by stephane-caron** [comment]
Your second error is due to Clarabel trying to compile from source (in which case you would need to install `cmake`, and probably other build tools). And indeed, as of today, Clarabel and OSQP [don't distribute wheels for aarch64 macOS](https://pypi.org/project/osqp/#files), which I'm guessing is the architecture of your computer (a.k.a. ARM-based or Apple Silicon). 

Does it work on your machine if you pip-install the following set of solvers instead?

```console
pip install qpsolvers[cvxopt,daqp,proxqp]
```

**Comment by BarshaLamichhane** [comment]
Hi, 

`pip install qpsolvers[cvxopt,daqp,proxqp]` This command also shows the same error. I also did `pip install cmake` and tried `pip install qpsolvers[cvxopt,daqp,proxqp]` again. But again it shows the same error. Please help with this.

**Comment by stephane-caron** [comment]
> pip install qpsolvers[cvxopt,daqp,proxqp] This command also shows the same error.

Hmm that's unexpected, none of those depend on `qdldl` so you should not get the same error. :thinking: 

When reporting an error, please include the complete output from the pip-install command, not just an extract. (Full outputs are always helpful.)

Next, here are three separate commands you can try:

- ``pip install cvxopt``: if you get an error, open an issue [here](https://github.com/cvxopt/cvxopt/issues)
- ``pip install daqp``: if you get an error, open an issue [here](https://github.com/darnstrom/daqp/issues)
- ``pip install proxsuite``: if you get an error, open an issue [here](https://github.com/Simple-Robotics/proxsuite/issues)

If any of these commands succeed, you can use `qpsolvers` with the corresponding solver.

**Comment by BarshaLamichhane** [comment]
`pip install cvxopt` is installed successfully. But `pip install daqp` is giving the following error. 

`(Barsha) barshalamichhane@MOORE-01 resultats % pip install daqp
Collecting daqp
  Using cached daqp-0.5.1.tar.gz (132 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: daqp
  Building wheel for daqp (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for daqp (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Could not find daqp directory
      running bdist_wheel
      running build
      running build_ext
      building 'daqp' extension
      error: unknown file type '.pxd' (from 'daqp.pxd')
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for daqp
Failed to build daqp
ERROR: Could not build wheels for daqp, which is required to install pyproject.toml-based projects
(Barsha) barshalamichhane@MOORE-01 resultats %    `


However `pip install cvxopt` worked for me and now qpsolvers is working as you mentioned. Thank you! 

BUT _`pip install daqp`: if you get an error, open an issue [here](https://github.com/darnstrom/daqp/issues)_ as you mentioned in the comment , I did not find any description/solution written for this issue in the provided link here. Please check for this. 

THANK YOU :)

**Comment by stephane-caron** [comment]
OK great :+1:

> BUT pip install daqp: if you get an error, open an issue [here](https://github.com/darnstrom/daqp/issues) as you mentioned in the comment , I did not find any description/solution written for this issue in the provided link here. Please check for this.

Ah right, my mistake. You have Python 3.12+ and DAQP does not have wheels for it yet. The relevant issue is then https://github.com/darnstrom/daqp/issues/32.
